### PR TITLE
Removed Readme broken links

### PR DESCRIPTION
**Pull request by afhamu**

### CODE REVIEW

**Comment by afhamu** [comment]
I have created a pull request against issue #3

**Comment by Nargonath** [comment]
Sorry I was long to come back and review the PR. Why did you close the PR @afhamu?

**Comment by afhamu** [comment]
I'm sorry it wasn't intentional. I was cleaning up my repositories and unfortunately this is among the ones I deleted. But I can quickly bring it back.

**Comment by Nargonath** [comment]
Sure, you can do so and I'll merge it. Thanks. 👍

**Comment by Marsup** [comment]
Thanks, but it won't be necessary, I published the tlds docs instead, all links seem valid now.

**Comment by Nargonath** [comment]
Ok, thanks @Marsup. I tried to find it initially but couldn't. I missed it. 😅

**Pull request closed without merging**
